In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
from matplotlib.ticker import FuncFormatter
import numpy as np

%matplotlib inline

# Famous people on Wikipedia

**Source:** Pantheon 1.0, a manually verified dataset of globally famous biographies.

In [2]:
df = pd.read_csv('pantheon.tsv', sep='\t')
df.head()

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
0,307,Abraham Lincoln,131,Hodgenville,KY,UNITED STATES,US,USA,37.571111,-85.738611,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,66145211,5.801387,586914.72200,41477236,24667975,504925.2748,27.938585
1,308,Aristotle,152,Stageira,NaN,Greece,GR,GRC,40.333333,23.500000,...,PHILOSOPHER,PHILOSOPHY,HUMANITIES,56355172,11.914597,201067.46070,15745351,40609821,370757.7105,31.993795
2,339,Ayn Rand,55,Saint Petersburg,NaN,Russia,RU,RUS,59.950000,30.300000,...,WRITER,LANGUAGE,HUMANITIES,14208218,3.175685,87632.49020,11023490,3184728,258331.2364,24.325936
3,595,Andre Agassi,69,Las Vegas,NV,UNITED STATES,US,USA,36.121514,-115.173851,...,TENNIS PLAYER,INDIVIDUAL SPORTS,SPORTS,11244030,6.242525,85553.31810,6353888,4890142,162956.9565,20.925999
4,628,Aldous Huxley,62,Godalming,NaN,UNITED KINGDOM,GB,GBR,51.185000,-0.610000,...,WRITER,LANGUAGE,HUMANITIES,9268920,6.219842,33037.03209,5137256,4131664,149498.7097,25.996605

**Who has the highest number of pageviews?**

In [4]:
df.sort_values(by='TotalPageViews', ascending=False).head(1)
#or df[['name', 'TotalPageViews']].sort_values(by='TotalPageViews', ascending=False).head(1)

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
10682,14995351,Michael Jackson,147,Gary,IN,UNITED STATES,US,USA,41.595556,-87.345278,...,MUSICIAN,MUSIC,ARTS,145250649,8.384906,3368345.812,67216609,78034040,988099.6531,25.524717

## Top 100

In [5]:
top100 = df.sort_values(by='TotalPageViews', ascending=False).head(100)
top100.head()

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
10682,14995351,Michael Jackson,147,Gary,IN,UNITED STATES,US,USA,41.595556,-87.345278,...,MUSICIAN,MUSIC,ARTS,145250649,8.384906,3.368346e+06,67216609,78034040,9.880997e+05,25.524717
9696,2731583,Adolf Hitler,169,Braunau am Inn,NaN,AUSTRIA,AT,AUT,48.258333,13.035000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,128368798,11.134763,4.333580e+05,52363146,76005652,7.595787e+05,30.577820
11073,23680998,Justin Bieber,94,London,NaN,CANADA,CA,CAN,42.983700,-81.249700,...,SINGER,MUSIC,ARTS,113558067,6.771105,1.171018e+06,59787119,53770948,1.208065e+06,19.392227
7346,534366,Barack Obama,200,Honolulu,HI,UNITED STATES,US,USA,21.300000,-157.816667,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,112536577,5.514038,1.409147e+06,72672000,39864577,5.626829e+05,24.889032
10007,4429395,Eminem,83,Saint Joseph,MO,UNITED STATES,US,USA,39.758056,-94.836667,...,SINGER,MUSIC,ARTS,108953700,5.623833,5.278025e+05,66505927,42447773,1.312695e+06,23.298848

In [5]:
top100.occupation.value_counts()

ACTOR                 29
SINGER                18
POLITICIAN             8
MUSICIAN               8
PHILOSOPHER            3
PAINTER                3
PHYSICIST              3
SOCIAL ACTIVIST        3
RELIGIOUS FIGURE       2
COMPOSER               2
SOCCER PLAYER          2
BUSINESSPERSON         2
INVENTOR               2
NOBLEMAN               2
BASKETBALL PLAYER      1
CELEBRITY              1
ECONOMIST              1
PSYCHOLOGIST           1
EXPLORER               1
WRESTLER               1
ASTRONOMER             1
WRITER                 1
DESIGNER               1
EXTREMIST              1
MILITARY PERSONNEL     1
BIOLOGIST              1
FILM DIRECTOR          1
Name: occupation, dtype: int64

## Brazil

In [4]:
dfbr = df[df['countryCode'] == 'BR']
dfbr.head()
dfbr.shape

(136, 23)

**Sorted by number of pageviews**

In [7]:
dfbr.sort_values(by='TotalPageViews', ascending=False)

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
2713,66164,Ronaldo,75,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,38313289,11.197644,210732.889400,14546961,23766328,510843.853300,22.533707
7319,524577,Ronaldinho,77,Porto Alegre,NaN,BRAZIL,BR,BRA,-30.033056,-51.230000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,38309688,10.687282,212406.266700,14213401,24096287,497528.415600,21.865202
10695,15326144,Neymar da Silva,49,Mogi das Cruzes,NaN,BRAZIL,BR,BRA,-23.522778,-46.193056,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,29245139,10.989705,477557.581200,9657964,19587175,596839.571400,18.113441
8894,1297124,Kaká,71,Brasilia,NaN,BRAZIL,BR,BRA,-16.019444,-48.066944,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,26741890,9.054374,174290.648200,11185649,15556241,376646.338000,20.688166
1275,24953,Pelé,88,Três Corações,NaN,BRAZIL,BR,BRA,-21.694722,-45.255278,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,24153197,10.422685,125882.721700,8748518,15404679,274468.147700,27.446571
3734,146638,Ayrton Senna,64,São Paulo,NaN,BRAZIL,BR,BRA,-23.550000,-46.633333,...,RACECAR DRIVER,INDIVIDUAL SPORTS,SPORTS,18835095,9.530541,102857.616400,6642249,12192846,294298.359400,24.098599
8450,928959,Adriana Lima,47,Salvador,NaN,BRAZIL,BR,BRA,-12.974722,-38.476667,...,MODEL,MEDIA PERSONALITY,PUBLIC FIGURE,18812150,5.990278,82749.511280,10388392,8423758,400258.510600,19.808055
8446,926934,Gisele Bündchen,52,Três de Maio,NaN,BRAZIL,BR,BRA,-27.772778,-54.240000,...,MODEL,MEDIA PERSONALITY,PUBLIC FIGURE,16507588,4.939023,89989.747020,10065441,6442147,317453.615400,19.398480
2682,65145,Paulo Coelho,69,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,WRITER,LANGUAGE,HUMANITIES,14311386,10.698883,72606.512690,4185642,10125744,207411.391300,26.192696
8773,1172821,Robinho,54,São Vicente,NaN,Brazil,BR,BRA,-23.963333,-46.392222,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,11302903,9.381606,74361.763020,4554307,6748596,209313.018500,19.271635
10398,8021453,Alexandre Rodrigues da Silva,46,Pato Branco,NaN,BRAZIL,BR,BRA,-26.216667,-52.666667,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,10376487,8.340212,63314.058090,4123265,6253222,225575.804300,18.141914
8452,929522,Alessandra Ambrosio,36,Erechim,NaN,BRAZIL,BR,BRA,-27.633889,-52.273889,...,MODEL,MEDIA PERSONALITY,PUBLIC FIGURE,9365378,4.931060,46320.998700,5540450,3824928,260149.388900,18.440065
5555,258947,Rivaldo,52,Paulista,NaN,BRAZIL,BR,BRA,-7.940833,-34.872778,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,9225397,10.983897,42095.491970,3161879,6063518,177411.480800,21.614502
11304,33150509,Michel Teló,34,Medianeira,NaN,BRAZIL,BR,BRA,-25.295000,-54.093889,...,SINGER,MUSIC,ARTS,8183024,7.759886,266653.438700,2810133,5372891,240677.176500,17.290834
10391,7977772,Dilma Rousseff,74,Belo Horizonte,NaN,BRAZIL,BR,BRA,-19.916667,-43.933333,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,7744700,5.207525,118713.687800,1892209,5852491,104658.108100,23.888700
3408,99328,Luiz Inácio Lula da Silva,80,Caetés,Pernambuco,BRAZIL,BR,BRA,-8.772800,-36.622800,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,7558871,5.820781,54144.537440,1628304,5930567,94485.887500,25.159262
8755,1142467,Adriano Leite Ribeiro,48,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,7467240,9.064991,32113.238820,2583921,4883319,155567.500000,19.554972
2093,48372,Oscar Niemeyer,68,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,ARCHITECT,DESIGN,ARTS,6674328,7.823341,114605.368400,1498447,5175881,98151.882350,24.887963
7642,615807,Romário,45,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,6366053,11.084890,28579.345510,1852390,4513663,141467.844400,22.155830
7939,711941,Deco,48,São Bernardo do Campo,NaN,Brazil,BR,BRA,-23.700000,-46.550000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,5718408,8.468332,29190.321090,2551102,3167306,119133.500000,19.704689
9874,3508785,Daniel Alves,47,Juazeiro,NaN,BRAZIL,BR,BRA,-9.430556,-40.502778,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,5635706,10.342055,35268.403130,2006757,3628949,119908.638300,18.827204
7644,615810,Zico,44,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,5622197,10.620073,23723.771810,1405370,4216827,127777.204500,24.117737
7693,618870,Paulo Freire,28,Recife,NaN,BRAZIL,BR,BRA,-8.050000,-34.900000,...,PHILOSOPHER,PHILOSOPHY,HUMANITIES,5570496,4.501691,20925.311120,1379660,4190836,198946.285700,24.654463
11085,23809308,Getúlio Vargas,39,São Borja,NaN,BRAZIL,BR,BRA,-28.650000,-56.000000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,5510071,2.450816,35012.479980,496203,5013868,141283.871800,24.286374
7063,454123,Roberto Carlos da Silva,56,Garça,Sao Paulo,Brazil,BR,BRA,-22.215278,-49.651111,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,5347640,11.923369,36149.277850,109516,5238124,95493.571430,21.070663
9273,1756817,Rodrigo Santoro,28,Petrópolis,NaN,BRAZIL,BR,BRA,-22.505000,-43.178889,...,ACTOR,FILM AND THEATRE,ARTS,5339883,5.143577,27830.211760,2765086,2574797,190710.107100,18.763940
10475,9262402,David Luiz Moreira Marinho,38,Diadema,NaN,BRAZIL,BR,BRA,-23.686111,-46.610556,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,5001708,8.401143,77968.153660,2258790,2742918,131623.894700,16.539561
9799,3122533,Juninho Pernambucano,35,Recife,NaN,BRAZIL,BR,BRA,-8.050000,-34.900000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,4993061,9.263602,25547.224260,1787411,3205650,142658.885700,19.813011
9438,2110277,Diego Ribas da Cunha,33,Ribeirão Preto,NaN,BRAZIL,BR,BRA,-21.178333,-47.806667,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,4962054,7.794390,32146.057530,1640049,3322005,150365.272700,17.732288
8981,1399716,Júlio César Soares Espíndola,43,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.785833,-43.311944,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,4888706,9.361644,57686.916390,1718020,3170686,113690.837200,18.531140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9804,3139959,Luisão,30,Amparo,NaN,BRAZIL,BR,BRA,-22.703056,-46.765000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,1020224,7.900113,6707.903223,412596,607628,34007.466670,16.604646
9160,1596378,Aldair,27,Ilhéus,NaN,Brazil,BR,BRA,-14.788889,-39.048889,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,995816,8.062511,3302.469241,338484,657332,36882.074070,19.860856
7510,579541,João Havelange,34,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,BUSINESSPERSON,BUSINESS,BUSINESS & LAW,989001,8.167627,9038.593279,343706,645295,29088.264710,22.722484
7213,492058,Ernesto Geisel,29,Bento Gonçalves,NaN,Brazil,BR,BRA,-29.170833,-51.518889,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,932978,3.502989,5933.893185,119680,813298,32171.655170,22.374760
10501,9856359,Roger Guerreiro,28,São Paulo,NaN,Brazil,BR,BRA,-23.550000,-46.633333,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,914476,4.807108,14599.370770,242540,671936,32659.857140,15.086595
8876,1275236,Jairzinho,32,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,894854,9.933421,4002.030332,334110,560744,27964.187500,23.043258
9866,3461720,Humberto de Alencar Castelo Branco,29,Fortaleza,NaN,BRAZIL,BR,BRA,-3.718333,-38.542778,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,884783,3.174802,6594.681835,77006,807777,30509.758620,22.175986
5507,254397,Maria II of Portugal,31,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,880468,5.147712,2710.025647,278065,602403,28402.193550,23.688007
8488,947100,João Baptista de Oliveira Figueiredo,30,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,867352,2.763209,6865.941086,67704,799648,28911.733330,21.856651
8487,947043,Emílio Garrastazu Médici,26,Bagé,NaN,Brazil,BR,BRA,-31.320000,-54.106944,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,856008,2.900058,5983.708147,70159,785849,32923.384620,21.961364
10011,4444669,Rodrigo Taddei,27,São Paulo,NaN,Brazil,BR,BRA,-23.550000,-46.633333,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,855712,6.752734,3423.323659,266692,589020,31693.037040,16.973138
9223,1686258,Alessandro Faiolhe Amantino Mancini,27,Ipatinga,NaN,BRAZIL,BR,BRA,-19.500000,-42.533333,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,840533,6.082783,6798.108684,31827,808706,31130.851850,16.481698
10609,12627202,Cesar Cielo Filho,28,Santa Bárbara d'Oeste,NaN,BRAZIL,BR,BRA,-22.754444,-47.414167,...,SWIMMER,INDIVIDUAL SPORTS,SPORTS,818425,5.562095,13966.407540,218343,600082,29229.464290,14.211567
8481,945885,Floriano Peixoto,32,Maceió,NaN,BRAZIL,BR,BRA,-9.665833,-35.735000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,721248,2.938221,3383.153924,55478,665770,22539.000000,22.759220
9693,2716670,Edmílson Gomes,28,Taquaritinga,NaN,BRAZIL,BR,BRA,-21.405833,-48.505000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,717759,11.009126,2850.840358,478,717281,25634.250000,18.356447
7643,615809,Djalma Santos,28,São Paulo,NaN,Brazil,BR,BRA,-15.783333,-47.866667,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,711016,9.245030,5859.309746,248820,462196,25393.428570,22.318191
11271,30871737,Valdir Pereira,27,Campos dos Goytacazes,NaN,BRAZIL,BR,BRA,-21.753889,-41.323889,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,679837,10.660671,3026.969668,1447,678390,25179.148150,23.432196
11188,26606111,Nathalia Dill,96,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,ACTOR,FILM AND THEATRE,ARTS,665485,4.503506,8855.522854,42548,622937,6932.135417,15.688800
4185,163094,Eurico Gaspar Dutra,27,Cuiabá,NaN,BRAZIL,BR,BRA,-15.595833,-56.096944,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,657041,2.683388,4457.293158,59642,597399,24334.851850,21.810980
9818,3162837,Vavá,28,Recife,NaN,BRAZIL,BR,BRA,-8.050000,-34.900000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,651973,10.409518,2621.136057,178229,473744,23284.750000,23.134967
7468,566796,Nílton Santos,27,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,630414,8.512652,6560.168267,218095,412319,23348.666670,21.885353
11155,25792280,Zilda Arns,28,Forquilhinha,NaN,BRAZIL,BR,BRA,-28.764167,-49.472222,...,PHYSICIAN,MEDICINE,SCIENCE & TECHNOLOGY,610647,3.476636,18767.041840,95636,515011,21808.821430,20.087854
10039,4691999,Paulo Mendes da Rocha,26,Vitória,NaN,BRAZIL,BR,BRA,-20.318889,-40.337778,...,ARCHITECT,DESIGN,ARTS,547319,7.462139,2399.273462,120573,426746,21050.730770,22.589778
10010,4444488,Donieber Alexander Marangon,31,Jundiaí,NaN,BRAZIL,BR,BRA,-23.186389,-46.884167,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,536552,10.304441,5653.730429,523,536029,17308.129030,16.635562
8482,945927,Francisco de Paula Rodrigues Alves,26,Guaratinguetá,NaN,BRAZIL,BR,BRA,-22.816667,-45.227778,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,487729,2.601134,2102.706163,36043,451686,18758.807690,22.087816
8483,946040,Washington Luís Pereira de Sousa,28,Macaé,NaN,BRAZIL,BR,BRA,-22.370833,-41.786944,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,423111,2.838098,3192.995524,25977,397134,15111.107140,21.462339
9951,4095564,Lucas di Grassi,28,São Paulo,NaN,BRAZIL,BR,BRA,-23.550000,-46.633333,...,RACECAR DRIVER,INDIVIDUAL SPORTS,SPORTS,396145,9.688934,4164.384080,125071,271074,14148.035710,14.963729
4422,172002,Peter Medawar,35,Petrópolis,NaN,BRAZIL,BR,BRA,-22.505000,-43.178889,...,BIOLOGIST,NATURAL SCIENCES,SCIENCE & TECHNOLOGY,392202,8.299716,1523.507145,195655,196547,11205.771430,22.441677
8271,837871,Afonso Augusto Moreira Pena,27,Santa Bárbara,NaN,BRAZIL,BR,BRA,-19.950000,-43.415000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,329457,3.450189,2519.263406,27171,302286,12202.111110,21.437728
9707,2785051,Ronald Golias,56,São Carlos,NaN,BRAZIL,BR,BRA,-22.017778,-47.890833,...,COMEDIAN,FILM AND THEATRE,ARTS,297130,5.264437,2150.482999,20482,276648,5305.892857,22.064797

In [25]:
dfbr.columns

Index(['en_curid', 'name', 'numlangs', 'birthcity', 'birthstate',
       'countryName', 'countryCode', 'countryCode3', 'LAT', 'LON',
       'continentName', 'birthyear', 'gender', 'occupation', 'industry',
       'domain', 'TotalPageViews', 'L_star', 'StdDevPageViews',
       'PageViewsEnglish', 'PageViewsNonEnglish', 'AverageViews', 'HPI'],
      dtype='object')

**When were most of these people born?**

In [26]:
dfbr.birthyear.value_counts()

1981    10
1980    7
1982    7
1984    7
1976    7
1983    5
1979    5
1929    4
1987    4
1986    3
1988    3
1973    3
1931    2
1972    2
1947    2
1934    2
1930    2
1928    2
1977    2
1839    2
1966    2
1975    2
1907    2
1944    2
1942    2
1946    2
1965    1
1960    1
1985    1
1969    1
       ..
1918    1
1992    1
1873    1
1883    1
1945    1
1887    1
1949    1
1963    1
1970    1
1989    1
1897    1
1916    1
1921    1
1910    1
1825    1
1882    1
1847    1
1902    1
1974    1
1919    1
1943    1
1925    1
1990    1
1905    1
1912    1
1915    1
1952    1
1953    1
1827    1
1819    1
Name: birthyear, Length: 69, dtype: int64

**Gender**

Spoiler alert: only 8% of them are women!

In [27]:
dfbr.gender.value_counts()

Male      125
Female    11
Name: gender, dtype: int64

In [84]:
dfbr[dfbr['gender'] == 'Female'].TotalPageViews.mean()

5446091.636363637

In [85]:
dfbr[dfbr['gender'] == 'Male'].TotalPageViews.mean()

4063257.992

In [138]:
brazil50 = dfbr.sort_values(by='TotalPageViews', ascending=False).head(50)
brazil50.to_csv('brasil50.csv')

In [5]:
brazil100 = dfbr.sort_values(by='TotalPageViews', ascending=False).head(100)
#brazil100.to_csv('brasil100.csv')

In [9]:
brazil100[brazil100['domain'] == 'SPORTS'].occupation.value_counts()

SOCCER PLAYER     60
RACECAR DRIVER     6
COACH              2
TENNIS PLAYER      1
Name: occupation, dtype: int64

**What's their occupation?**

In [37]:
dfbr.occupation.value_counts()

# SOCCER SOCCER AND SOCCER

SOCCER PLAYER     77
POLITICIAN        22
RACECAR DRIVER    7
MUSICIAN          4
COACH             3
MODEL             3
ACTOR             3
WRITER            3
SINGER            2
ARCHITECT         2
BUSINESSPERSON    1
BIOLOGIST         1
PHYSICIAN         1
COMPOSER          1
COMEDIAN          1
INVENTOR          1
PHILOSOPHER       1
SWIMMER           1
PRESENTER         1
TENNIS PLAYER     1
Name: occupation, dtype: int64

**What's their average age?**

In [72]:
dfbr.birthyear.astype(int).mean()

1952.9264705882354

In [73]:
2018 - 1952

66

## US

In [20]:
dfus = df[df['countryCode'] == 'US']

In [22]:
ustop50 = dfus.sort_values(by='TotalPageViews', ascending=False).head(50)

In [41]:
dfus.sort_values(by='TotalPageViews', ascending=False).head(150).occupation.value_counts()

# much more pop culture and politics 
# mostly actors, singers and politicians

ACTOR                 72
SINGER                28
POLITICIAN            12
MUSICIAN              7
FILM DIRECTOR         4
WRESTLER              3
BASKETBALL PLAYER     3
WRITER                3
BUSINESSPERSON        3
BOXER                 2
PORNOGRAPHIC ACTOR    2
CELEBRITY             2
SOCIAL ACTIVIST       2
MAFIOSO               1
ARTIST                1
INVENTOR              1
ASTRONAUT             1
PRODUCER              1
EXTREMIST             1
DESIGNER              1
Name: occupation, dtype: int64

In [42]:
dfus.sort_values(by='TotalPageViews', ascending=False).head(150).gender.value_counts()

Male      101
Female    49
Name: gender, dtype: int64

In [44]:
dfus.sort_values(by='TotalPageViews', ascending=False).head(20)

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
10682,14995351,Michael Jackson,147,Gary,IN,UNITED STATES,US,USA,41.595556,-87.345278,...,MUSICIAN,MUSIC,ARTS,145250649,8.384906,3.368346e+06,67216609,78034040,9.880997e+05,25.524717
7346,534366,Barack Obama,200,Honolulu,HI,UNITED STATES,US,USA,21.300000,-157.816667,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,112536577,5.514038,1.409147e+06,72672000,39864577,5.626829e+05,24.889032
10007,4429395,Eminem,83,Saint Joseph,MO,UNITED STATES,US,USA,39.758056,-94.836667,...,SINGER,MUSIC,ARTS,108953700,5.623833,5.278025e+05,66505927,42447773,1.312695e+06,23.298848
9093,17782843,Lady Gaga,133,New York,NY,UNITED STATES,US,USA,40.712700,-74.005900,...,MUSICIAN,MUSIC,ARTS,104562647,6.899731,1.002622e+06,56998631,47564016,7.861853e+05,21.104507
10407,8135890,Miley Cyrus,72,Nashville,TN,UNITED STATES,US,USA,36.166667,-86.783333,...,ACTOR,FILM AND THEATRE,ARTS,91947733,6.703494,3.729421e+05,48648525,43299208,1.277052e+06,20.189985
10286,6844407,Selena Gomez,96,Grand Prairie,TX,United States,US,USA,32.715278,-97.016944,...,SINGER,MUSIC,ARTS,87742946,6.739624,5.774936e+05,45645833,42097113,9.139890e+05,19.970804
2865,71870,Johnny Depp,80,Owensboro,KY,UNITED STATES,US,USA,37.757748,-87.118390,...,ACTOR,FILM AND THEATRE,ARTS,83016743,8.015574,4.120442e+05,36362738,46654005,1.037709e+06,25.115469
10202,7412236,Steve Jobs,122,San Francisco-Bay Area,CA,UNITED STATES,US,USA,37.783333,-122.416667,...,DESIGNER,DESIGN,ARTS,78372660,6.253179,2.303999e+06,45627865,32744795,6.423989e+05,24.406233
7081,5792809,Angelina Jolie,91,Los Angeles,CA,UNITED STATES,US,USA,34.050000,-118.250000,...,ACTOR,FILM AND THEATRE,ARTS,68213700,7.665655,3.002520e+05,34643640,33570060,7.496011e+05,23.078402
7162,19394613,Kim Kardashian,44,Los Angeles,CA,UNITED STATES,US,USA,34.050000,-118.250000,...,CELEBRITY,MEDIA PERSONALITY,PUBLIC FIGURE,66670205,3.628775,3.805552e+05,47834822,18835383,1.515232e+06,19.950031
0,307,Abraham Lincoln,131,Hodgenville,KY,UNITED STATES,US,USA,37.571111,-85.738611,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,66145211,5.801387,5.869147e+05,41477236,24667975,5.049253e+05,27.938585
4344,168540,Lil Wayne,46,New Orleans,LA,United States,US,USA,NaN,NaN,...,SINGER,MUSIC,ARTS,64484487,2.563680,1.919328e+05,52129870,12354617,1.401837e+06,19.545664
4232,19318,Marilyn Monroe,143,Los Angeles,CA,United States,US,USA,34.050000,-118.250000,...,ACTOR,FILM AND THEATRE,ARTS,63671491,8.509241,4.296378e+05,31088742,32582749,4.452552e+05,28.346646
10937,2844938,Mark Zuckerberg,85,Lower Hudson Valley,NY,United States,US,USA,41.040000,-73.778611,...,BUSINESSPERSON,BUSINESS,BUSINESS & LAW,62640549,5.167148,9.535541e+05,39243182,23397367,7.369476e+05,19.533260
10429,16477368,Katy Perry,72,Santa Barbara,CA,UNITED STATES,US,USA,34.425833,-119.714167,...,SINGER,MUSIC,ARTS,61762831,5.347606,3.990784e+05,36463275,25299556,8.578171e+05,20.336693
3382,31341,Tupac Shakur,69,New York,NY,United States,US,USA,NaN,NaN,...,SINGER,MUSIC,ARTS,59789956,5.296006,2.001476e+05,36806550,22983406,8.665211e+05,22.970373
9279,1769827,Megan Fox,63,Oak Ridge,TN,UNITED STATES,US,USA,36.013333,-84.262500,...,ACTOR,FILM AND THEATRE,ARTS,59594557,5.225347,3.732418e+05,33823561,25770996,9.459453e+05,19.892430
10152,5422144,Taylor Swift,68,Reading,PA,United States,US,USA,40.341667,-75.926389,...,ACTOR,FILM AND THEATRE,ARTS,58688243,4.900938,4.224973e+05,37700341,20987902,8.630624e+05,19.046589
179,3382,Britney Spears,94,McComb,MS,UNITED STATES,US,USA,31.244472,-90.471592,...,SINGER,MUSIC,ARTS,58474806,7.014088,1.817315e+05,30872137,27602669,6.220724e+05,22.193222
4626,5119376,John F. Kennedy,116,Boston,MA,UNITED STATES,US,USA,42.331667,-71.121667,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,57596834,6.577612,3.902760e+05,33052400,24544434,4.965244e+05,27.663441

**What's their average age?**

In [9]:
df.dtypes

en_curid                 int64
name                    object
numlangs                 int64
birthcity               object
birthstate              object
countryName             object
countryCode             object
countryCode3            object
LAT                    float64
LON                    float64
continentName           object
birthyear               object
gender                  object
occupation              object
industry                object
domain                  object
TotalPageViews           int64
L_star                 float64
StdDevPageViews        float64
PageViewsEnglish         int64
PageViewsNonEnglish      int64
AverageViews           float64
HPI                    float64
dtype: object

In [74]:
dfus.birthyear.astype(int).mean()

1936.222683264177

In [75]:
2018 - 1936

# US famous people are in average much older than Brazilians

82

In [86]:
dfus[dfus['gender'] == 'Female'].TotalPageViews.mean()

11293466.982889734

In [23]:
ustop50[ustop50['gender'] == 'Female'].TotalPageViews.mean()

62447877.941176474

In [87]:
dfbr[dfbr['gender'] == 'Male'].TotalPageViews.mean()

4063257.992

In [24]:
ustop50[ustop50['gender'] == 'Male'].TotalPageViews.mean()

57884173.81818182

## Canada

In [76]:
dfcanada = df[df['countryCode'] == 'CA']
dfcanada.head()

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
306,7892,David Cronenberg,38,Toronto,NaN,CANADA,CA,CAN,43.700000,-79.400000,...,FILM DIRECTOR,FILM AND THEATRE,ARTS,5338747,5.761051,25160.278470,2541892,2796855,140493.34210,24.378167
670,15587,Joshua Jackson,31,Vancouver,NaN,CANADA,CA,CAN,49.250000,-123.100000,...,ACTOR,FILM AND THEATRE,ARTS,9380359,4.892921,40373.742230,5209992,4170367,302592.22580,19.001460
674,15622,James Cameron,70,Kapuskasing,NaN,CANADA,CA,CAN,49.416667,-82.433333,...,FILM DIRECTOR,FILM AND THEATRE,ARTS,20317098,5.477146,228978.001300,12182491,8134607,290244.25710,23.439536
704,15915,John Diefenbaker,29,Neustadt,NaN,Canada,CA,CAN,44.080000,-81.000000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1073646,2.446013,5416.431512,879111,194535,37022.27586,20.894157
759,16278,James Randi,30,Toronto,NaN,Canada,CA,CAN,43.700000,-79.400000,...,MAGICIAN,MEDIA PERSONALITY,PUBLIC FIGURE,3165096,3.983276,11001.530990,2208093,957003,105503.20000,23.144797

In [60]:
dfcanada.sort_values(by='TotalPageViews', ascending=False).head(20)

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
11073,23680998,Justin Bieber,94,London,NaN,CANADA,CA,CAN,42.983700,-81.249700,...,SINGER,MUSIC,ARTS,113558067,6.771105,1.171018e+06,59787119,53770948,1.208065e+06,19.392227
4267,165507,Avril Lavigne,103,Belleville,NaN,CANADA,CA,CAN,44.166667,-77.383333,...,MUSICIAN,MUSIC,ARTS,43963702,8.458331,2.050534e+05,19626538,24337164,4.268321e+05,21.440427
3237,86665,Jim Carrey,74,Newmarket,NaN,CANADA,CA,CAN,44.060000,-79.450000,...,ACTOR,FILM AND THEATRE,ARTS,36248249,6.425185,1.513707e+05,19508404,16739845,4.898412e+05,24.121268
7999,731111,Ryan Reynolds,38,Vancouver,NaN,CANADA,CA,CAN,49.250000,-123.100000,...,ACTOR,FILM AND THEATRE,ARTS,33408554,4.090046,1.872512e+05,21685218,11723336,8.791725e+05,20.121125
8374,891226,Ryan Gosling,37,London,NaN,CANADA,CA,CAN,42.983700,-81.249700,...,ACTOR,FILM AND THEATRE,ARTS,31058128,4.810677,3.637490e+05,17959836,13098292,8.394089e+05,18.976717
8111,760163,Rachel McAdams,41,London,NaN,CANADA,CA,CAN,42.983700,-81.249700,...,ACTOR,FILM AND THEATRE,ARTS,25704275,4.396779,1.711354e+05,15782072,9922203,6.269335e+05,19.604663
2788,68904,Michael J. Fox,50,Edmonton,NaN,Canada,CA,CAN,53.533333,-113.500000,...,ACTOR,FILM AND THEATRE,ARTS,23391970,6.090737,1.092861e+05,12072882,11319088,4.678394e+05,23.329097
4889,203407,Celine Dion,76,Charlemagne,NaN,CANADA,CA,CAN,45.716667,-73.483333,...,SINGER,MUSIC,ARTS,22409500,7.086484,1.013690e+05,11516183,10893317,2.948618e+05,22.788887
6505,377337,Sunny Leone,27,Sarnia,NaN,CANADA,CA,CAN,42.999444,-82.308889,...,PORNOGRAPHIC ACTOR,MEDIA PERSONALITY,PUBLIC FIGURE,21407381,1.802878,3.324008e+05,19190809,2216572,7.928660e+05,15.456606
9546,2323727,Ellen Page,47,Halifax,NaN,CANADA,CA,CAN,44.670000,-63.610000,...,ACTOR,FILM AND THEATRE,ARTS,21285325,4.334711,1.363694e+05,13281803,8003522,4.528793e+05,18.050440
674,15622,James Cameron,70,Kapuskasing,NaN,CANADA,CA,CAN,49.416667,-82.433333,...,FILM DIRECTOR,FILM AND THEATRE,ARTS,20317098,5.477146,2.289780e+05,12182491,8134607,2.902443e+05,23.439536
1067,23035,Pamela Anderson,61,Ladysmith,NaN,CANADA,CA,CAN,48.997500,-123.820278,...,ACTOR,FILM AND THEATRE,ARTS,19552713,6.243481,5.348338e+04,11316913,8235800,3.205363e+05,22.824455
9767,2991300,Cobie Smulders,37,Vancouver,NaN,CANADA,CA,CAN,49.250000,-123.100000,...,ACTOR,FILM AND THEATRE,ARTS,18904652,3.894434,1.877290e+05,11952914,6951738,5.109365e+05,17.966136
10232,6064346,Cory Monteith,28,Calgary,NaN,CANADA,CA,CAN,51.050000,-114.066667,...,ACTOR,FILM AND THEATRE,ARTS,17613744,4.536724,6.066239e+05,10652703,6961041,6.290623e+05,16.597779
7706,621503,Michael Bublé,41,Burnaby,NaN,CANADA,CA,CAN,49.266667,-122.966667,...,SINGER,MUSIC,ARTS,16810260,3.882973,2.072379e+05,11547358,5262902,4.100063e+05,18.718112
5677,276341,Anna Paquin,40,Winnipeg,NaN,CANADA,CA,CAN,49.899444,-97.139167,...,ACTOR,FILM AND THEATRE,ARTS,16218077,4.027028,9.992046e+04,10757350,5460727,4.054519e+05,18.313511
10591,12310814,Carly Rae Jepsen,36,Mission,NaN,Canada,CA,CAN,49.133694,-122.311167,...,SINGER,MUSIC,ARTS,16168959,4.261300,4.346138e+05,10525892,5643067,4.491378e+05,16.322434
9275,1762258,Seth Rogen,32,Vancouver,NaN,CANADA,CA,CAN,49.250000,-123.100000,...,ACTOR,FILM AND THEATRE,ARTS,15609205,2.411853,6.262994e+04,12552769,3056436,4.877877e+05,17.426267
10693,15263646,deadmau5,29,Niagara Falls,NaN,CANADA,CA,CAN,43.116667,-79.066667,...,MUSICIAN,MUSIC,ARTS,15194843,2.727587,1.626821e+05,11838279,3356564,5.239601e+05,16.728818
2321,53736,Hayden Christensen,38,Vancouver,NaN,CANADA,CA,CAN,49.250000,-123.100000,...,ACTOR,FILM AND THEATRE,ARTS,14722691,5.362645,4.580729e+04,8122926,6599765,3.874392e+05,19.587053

**Ocupation**

Very similar to the US

In [79]:
dfcanada.sort_values(by='TotalPageViews', ascending=False).head(150).occupation.value_counts()

ACTOR                 39
SINGER                15
POLITICIAN            10
MUSICIAN              8
WRITER                6
ECONOMIST             4
WRESTLER              4
CHEMIST               4
PHYSICIST             3
PHYSICIAN             3
RACECAR DRIVER        2
FILM DIRECTOR         2
COMPOSER              2
PSYCHOLOGIST          2
PORNOGRAPHIC ACTOR    2
ARCHITECT             1
TENNIS PLAYER         1
PHILOSOPHER           1
HOCKEY PLAYER         1
SOCCER PLAYER         1
BIOLOGIST             1
ATHLETE               1
MAGICIAN              1
MODEL                 1
COMPUTER SCIENTIST    1
INVENTOR              1
Name: occupation, dtype: int64

In [83]:
dfargentina = df[df['countryCode'] == 'AR']
dfargentina.head(20)
#dfargentina.shape

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
331,8485,Diego Maradona,87,Buenos Aires,NaN,ARGENTINA,AR,ARG,-34.700000,-58.400000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,22634139,10.404085,161815.902300,7799370,14834769,260162.51720,24.420069
687,15781,Jorge Luis Borges,101,Buenos Aires,NaN,ARGENTINA,AR,ARG,-34.603333,-58.381667,...,WRITER,LANGUAGE,HUMANITIES,18357830,8.276086,680568.271800,5587162,12770668,181760.69310,25.525814
806,16588,Javier Saviola,42,Buenos Aires,NaN,ARGENTINA,AR,ARG,-34.603333,-58.381667,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,4715369,9.305682,26131.484180,1569493,3145876,112270.69050,18.920102
1806,42580,Leopoldo Galtieri,34,Buenos Aires,NaN,ARGENTINA,AR,ARG,-34.610556,-58.562500,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1036548,6.864223,7824.076515,354875,681673,30486.70588,22.716240
1933,44903,Ástor Piazzolla,47,Mar del Plata,NaN,ARGENTINA,AR,ARG,-38.000000,-57.550000,...,COMPOSER,MUSIC,ARTS,2913501,9.294964,11279.294680,640661,2272840,61989.38298,25.255418
2101,48532,Juan Manuel Fangio,49,Balcarce,NaN,ARGENTINA,AR,ARG,-37.845556,-58.257778,...,RACECAR DRIVER,INDIVIDUAL SPORTS,SPORTS,2390551,9.819377,11483.840320,781563,1608988,48786.75510,24.865179
2168,49966,Carlos Menem,43,Anillaco,La Rioja,Argentina,AR,ARG,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,2269838,4.941167,13379.839460,599898,1669940,52786.93023,23.731668
2224,51584,Eva Perón,73,Los Toldos,NaN,ARGENTINA,AR,ARG,-35.000000,-61.033333,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,11272900,7.020002,56450.141720,4666210,6606690,154423.28770,26.240244
2263,52395,Martha Argerich,35,Buenos Aires,NaN,ARGENTINA,AR,ARG,-34.603333,-58.381667,...,MUSICIAN,MUSIC,ARTS,1962527,7.630029,6402.218146,777348,1185179,56072.20000,24.106484
3459,102274,Princess Máxima of the Netherlands,30,Buenos Aires,NaN,Argentina,AR,ARG,-34.603333,-58.381667,...,COMPANION,COMPANIONS,PUBLIC FIGURE,3064498,6.354380,65488.184600,1042964,2021534,102149.93330,18.034971
3745,147041,Manu Ginóbili,32,Bahía Blanca,NaN,Argentina,AR,ARG,-38.716667,-62.266667,...,BASKETBALL PLAYER,TEAM SPORTS,SPORTS,3259981,3.871804,52490.453310,2067151,1192830,101874.40630,16.391295
4779,195152,Adolfo Pérez Esquivel,36,Buenos Aires,NaN,ARGENTINA,AR,ARG,-34.603333,-58.381667,...,SOCIAL ACTIVIST,ACTIVISM,PUBLIC FIGURE,800040,5.668345,7461.349375,114201,685839,22223.33333,22.333850
4809,196840,Eduardo Duhalde,29,Lomas de Zamora,NaN,Argentina,AR,ARG,-34.766667,-58.400000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,764141,4.494566,5072.098161,150368,613773,26349.68966,22.020839
4868,201160,Adolfo Bioy Casares,27,Buenos Aires,NaN,Argentina,AR,ARG,-34.590556,-58.390556,...,WRITER,LANGUAGE,HUMANITIES,1027110,3.714441,20705.527470,135533,891577,38041.11111,21.250928
4952,207775,Daniel Barenboim,34,Buenos Aires,NaN,Argentina,AR,ARG,-34.603333,-58.381667,...,CONDUCTOR,MUSIC,ARTS,2435090,7.758161,14377.941330,893833,1541257,71620.29412,23.753466
4974,209191,Isabel Martínez de Perón,40,La Rioja,NaN,ARGENTINA,AR,ARG,-29.412500,-66.854167,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1951362,6.876079,14820.260610,626017,1325345,48784.05000,23.496509
5202,230189,Néstor Kirchner,49,Río Gallegos,NaN,ARGENTINA,AR,ARG,-51.633333,-69.216667,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,3895349,5.111991,73032.947380,1145430,2749919,79496.91837,22.039093
5466,252453,Bernardo Houssay,33,Buenos Aires,NaN,Argentina,AR,ARG,-34.603333,-58.381667,...,PHYSICIAN,MEDICINE,SCIENCE & TECHNOLOGY,742617,3.584179,30172.469730,80775,661842,22503.54545,20.591043
5960,310344,Jorge Rafael Videla,41,Buenos Aires,NaN,Argentina,AR,ARG,-34.650000,-59.433333,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,2894243,6.367245,54442.224040,670866,2223377,70591.29268,23.105665
6110,323750,Carlos Saavedra Lamas,37,Buenos Aires,NaN,ARGENTINA,AR,ARG,-34.603333,-58.381667,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,442050,8.849657,2141.419251,64798,377252,11947.29730,23.223661

## Creating a df with a top 50 people for every country

In [3]:
alltop50 = df.sort_values(by='TotalPageViews', ascending=False).groupby('countryCode').head(50)

In [103]:
alltop50[alltop50['countryCode'] == 'BR']

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
2713,66164,Ronaldo,75,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,38313289,11.197644,210732.88940,14546961,23766328,510843.85330,22.533707
7319,524577,Ronaldinho,77,Porto Alegre,NaN,BRAZIL,BR,BRA,-30.033056,-51.230000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,38309688,10.687282,212406.26670,14213401,24096287,497528.41560,21.865202
10695,15326144,Neymar da Silva,49,Mogi das Cruzes,NaN,BRAZIL,BR,BRA,-23.522778,-46.193056,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,29245139,10.989705,477557.58120,9657964,19587175,596839.57140,18.113441
8894,1297124,Kaká,71,Brasilia,NaN,BRAZIL,BR,BRA,-16.019444,-48.066944,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,26741890,9.054374,174290.64820,11185649,15556241,376646.33800,20.688166
1275,24953,Pelé,88,Três Corações,NaN,BRAZIL,BR,BRA,-21.694722,-45.255278,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,24153197,10.422685,125882.72170,8748518,15404679,274468.14770,27.446571
3734,146638,Ayrton Senna,64,São Paulo,NaN,BRAZIL,BR,BRA,-23.550000,-46.633333,...,RACECAR DRIVER,INDIVIDUAL SPORTS,SPORTS,18835095,9.530541,102857.61640,6642249,12192846,294298.35940,24.098599
8450,928959,Adriana Lima,47,Salvador,NaN,BRAZIL,BR,BRA,-12.974722,-38.476667,...,MODEL,MEDIA PERSONALITY,PUBLIC FIGURE,18812150,5.990278,82749.51128,10388392,8423758,400258.51060,19.808055
8446,926934,Gisele Bündchen,52,Três de Maio,NaN,BRAZIL,BR,BRA,-27.772778,-54.240000,...,MODEL,MEDIA PERSONALITY,PUBLIC FIGURE,16507588,4.939023,89989.74702,10065441,6442147,317453.61540,19.398480
2682,65145,Paulo Coelho,69,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,WRITER,LANGUAGE,HUMANITIES,14311386,10.698883,72606.51269,4185642,10125744,207411.39130,26.192696
8773,1172821,Robinho,54,São Vicente,NaN,Brazil,BR,BRA,-23.963333,-46.392222,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,11302903,9.381606,74361.76302,4554307,6748596,209313.01850,19.271635
10398,8021453,Alexandre Rodrigues da Silva,46,Pato Branco,NaN,BRAZIL,BR,BRA,-26.216667,-52.666667,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,10376487,8.340212,63314.05809,4123265,6253222,225575.80430,18.141914
8452,929522,Alessandra Ambrosio,36,Erechim,NaN,BRAZIL,BR,BRA,-27.633889,-52.273889,...,MODEL,MEDIA PERSONALITY,PUBLIC FIGURE,9365378,4.931060,46320.99870,5540450,3824928,260149.38890,18.440065
5555,258947,Rivaldo,52,Paulista,NaN,BRAZIL,BR,BRA,-7.940833,-34.872778,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,9225397,10.983897,42095.49197,3161879,6063518,177411.48080,21.614502
11304,33150509,Michel Teló,34,Medianeira,NaN,BRAZIL,BR,BRA,-25.295000,-54.093889,...,SINGER,MUSIC,ARTS,8183024,7.759886,266653.43870,2810133,5372891,240677.17650,17.290834
10391,7977772,Dilma Rousseff,74,Belo Horizonte,NaN,BRAZIL,BR,BRA,-19.916667,-43.933333,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,7744700,5.207525,118713.68780,1892209,5852491,104658.10810,23.888700
3408,99328,Luiz Inácio Lula da Silva,80,Caetés,Pernambuco,BRAZIL,BR,BRA,-8.772800,-36.622800,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,7558871,5.820781,54144.53744,1628304,5930567,94485.88750,25.159262
8755,1142467,Adriano Leite Ribeiro,48,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,7467240,9.064991,32113.23882,2583921,4883319,155567.50000,19.554972
2093,48372,Oscar Niemeyer,68,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,ARCHITECT,DESIGN,ARTS,6674328,7.823341,114605.36840,1498447,5175881,98151.88235,24.887963
7642,615807,Romário,45,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,6366053,11.084890,28579.34551,1852390,4513663,141467.84440,22.155830
7939,711941,Deco,48,São Bernardo do Campo,NaN,Brazil,BR,BRA,-23.700000,-46.550000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,5718408,8.468332,29190.32109,2551102,3167306,119133.50000,19.704689
9874,3508785,Daniel Alves,47,Juazeiro,NaN,BRAZIL,BR,BRA,-9.430556,-40.502778,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,5635706,10.342055,35268.40313,2006757,3628949,119908.63830,18.827204
7644,615810,Zico,44,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,5622197,10.620073,23723.77181,1405370,4216827,127777.20450,24.117737
7693,618870,Paulo Freire,28,Recife,NaN,BRAZIL,BR,BRA,-8.050000,-34.900000,...,PHILOSOPHER,PHILOSOPHY,HUMANITIES,5570496,4.501691,20925.31112,1379660,4190836,198946.28570,24.654463
11085,23809308,Getúlio Vargas,39,São Borja,NaN,BRAZIL,BR,BRA,-28.650000,-56.000000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,5510071,2.450816,35012.47998,496203,5013868,141283.87180,24.286374
7063,454123,Roberto Carlos da Silva,56,Garça,Sao Paulo,Brazil,BR,BRA,-22.215278,-49.651111,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,5347640,11.923369,36149.27785,109516,5238124,95493.57143,21.070663
9273,1756817,Rodrigo Santoro,28,Petrópolis,NaN,BRAZIL,BR,BRA,-22.505000,-43.178889,...,ACTOR,FILM AND THEATRE,ARTS,5339883,5.143577,27830.21176,2765086,2574797,190710.10710,18.763940
10475,9262402,David Luiz Moreira Marinho,38,Diadema,NaN,BRAZIL,BR,BRA,-23.686111,-46.610556,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,5001708,8.401143,77968.15366,2258790,2742918,131623.89470,16.539561
9799,3122533,Juninho Pernambucano,35,Recife,NaN,BRAZIL,BR,BRA,-8.050000,-34.900000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,4993061,9.263602,25547.22426,1787411,3205650,142658.88570,19.813011
9438,2110277,Diego Ribas da Cunha,33,Ribeirão Preto,NaN,BRAZIL,BR,BRA,-21.178333,-47.806667,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,4962054,7.794390,32146.05753,1640049,3322005,150365.27270,17.732288
8981,1399716,Júlio César Soares Espíndola,43,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.785833,-43.311944,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,4888706,9.361644,57686.91639,1718020,3170686,113690.83720,18.531140
6064,319743,Joaquim Maria Machado de Assis,30,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,WRITER,LANGUAGE,HUMANITIES,4576905,1.596897,36498.58184,167705,4409200,152563.50000,23.444774
9545,2322845,Thiago Motta,38,São Bernardo do Campo,NaN,BRAZIL,BR,BRA,-23.700000,-46.550000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,4220031,7.857772,50606.77334,1470506,2749525,111053.44740,17.578544
9821,3168862,Eduardo da Silva,44,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,4078102,7.485271,37976.98387,2092008,1986094,92684.13636,17.437707
10289,6858503,Marcelo Vieira,43,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,3998307,9.420101,42135.46577,1350686,2647621,92983.88372,16.962645
7917,700574,Garrincha,47,Pau Grande,NaN,Brazil,BR,BRA,-22.584444,-43.169722,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,3950770,11.108546,17469.25987,945978,3004792,84058.93617,25.479102
7773,647263,Felipe Massa,57,São Paulo,NaN,BRAZIL,BR,BRA,-23.550000,-46.633333,...,RACECAR DRIVER,INDIVIDUAL SPORTS,SPORTS,3902306,10.569136,40085.83604,1440555,2461751,68461.50877,18.490435
9985,4288926,Anderson Luís de Abreu Oliveira,46,Porto Alegre,NaN,BRAZIL,BR,BRA,-30.033056,-51.230000,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,3835948,5.885047,13631.23465,2224018,1611930,83390.17391,17.150497
9161,1596818,Luís Fabiano,37,Campinas,NaN,BRAZIL,BR,BRA,-22.900833,-47.057222,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,3824730,8.672608,39985.35912,1477709,2347021,103371.08110,17.960291
7641,615800,Cafu,45,São Paulo,NaN,Brazil,BR,BRA,-23.550000,-46.633333,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,3806118,10.785598,14976.77961,1307444,2498674,84580.40000,21.033332
10568,11885871,Felipe Melo de Carvalho,35,Volta Redonda,NaN,BRAZIL,BR,BRA,-22.522778,-44.103889,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,3758381,7.846599,42144.54429,1033985,2724396,107382.31430,17.386317
10385,7934578,Thiago Emiliano da Silva,35,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,3587999,10.079757,57534.27829,1436,3586563,102514.25710,17.386733
5479,252989,Rubens Barrichello,50,São Paulo,NaN,BRAZIL,BR,BRA,-23.550000,-46.633333,...,RACECAR DRIVER,INDIVIDUAL SPORTS,SPORTS,3441875,9.016159,17412.90686,1418512,2023363,68837.50000,20.177126
6003,314055,Juscelino Kubitschek de Oliveira,39,Diamantina,NaN,BRAZIL,BR,BRA,-18.249000,-43.600000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,3370083,2.279152,20548.03262,207060,3163023,86412.38462,23.674873
9346,1896500,Lúcio,41,Brasilia,NaN,BRAZIL,BR,BRA,-15.619167,-47.652500,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,3314419,8.424250,35938.77804,1301075,2013344,80839.48780,18.172190
8067,751881,Luiz Felipe Scolari,39,Passo Fundo,NaN,BRAZIL,BR,BRA,-28.250000,-52.400000,...,COACH,TEAM SPORTS,SPORTS,3244065,7.999940,35690.45192,1307446,1936619,83181.15385,22.749381
8730,1129182,Leonardo Araújo,32,Niterói,NaN,Brazil,BR,BRA,-22.883333,-43.103611,...,COACH,TEAM SPORTS,SPORTS,3230236,7.241002,35125.58279,908999,2321237,100944.87500,19.363251
8212,794885,Vagner Love,28,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,3156572,8.524838,21834.60485,927079,2229493,112734.71430,17.361401
9368,1949483,Rogério Ceni,29,Pato Branco,NaN,BRAZIL,BR,BRA,-26.216667,-52.666667,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,3141694,7.346664,27585.45896,912750,2228944,108334.27590,18.812393
3926,152687,Alberto Santos-Dumont,30,Santos Dumont,NaN,BRAZIL,BR,BRA,-21.456667,-43.552500,...,INVENTOR,INVENTION,SCIENCE & TECHNOLOGY,2995065,3.381319,25010.59485,531689,2463376,99835.50000,23.409904
9452,2129433,Júlio Baptista,35,São Paulo,NaN,BRAZIL,BR,BRA,-23.550000,-46.633333,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,2990436,8.649334,18845.05789,1103272,1887164,85441.02857,18.025102

In [104]:
alltop50[alltop50['countryCode'] == 'US']

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
10682,14995351,Michael Jackson,147,Gary,IN,UNITED STATES,US,USA,41.595556,-87.345278,...,MUSICIAN,MUSIC,ARTS,145250649,8.384906,3.368346e+06,67216609,78034040,9.880997e+05,25.524717
7346,534366,Barack Obama,200,Honolulu,HI,UNITED STATES,US,USA,21.300000,-157.816667,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,112536577,5.514038,1.409147e+06,72672000,39864577,5.626829e+05,24.889032
10007,4429395,Eminem,83,Saint Joseph,MO,UNITED STATES,US,USA,39.758056,-94.836667,...,SINGER,MUSIC,ARTS,108953700,5.623833,5.278025e+05,66505927,42447773,1.312695e+06,23.298848
9093,17782843,Lady Gaga,133,New York,NY,UNITED STATES,US,USA,40.712700,-74.005900,...,MUSICIAN,MUSIC,ARTS,104562647,6.899731,1.002622e+06,56998631,47564016,7.861853e+05,21.104507
10407,8135890,Miley Cyrus,72,Nashville,TN,UNITED STATES,US,USA,36.166667,-86.783333,...,ACTOR,FILM AND THEATRE,ARTS,91947733,6.703494,3.729421e+05,48648525,43299208,1.277052e+06,20.189985
10286,6844407,Selena Gomez,96,Grand Prairie,TX,United States,US,USA,32.715278,-97.016944,...,SINGER,MUSIC,ARTS,87742946,6.739624,5.774936e+05,45645833,42097113,9.139890e+05,19.970804
2865,71870,Johnny Depp,80,Owensboro,KY,UNITED STATES,US,USA,37.757748,-87.118390,...,ACTOR,FILM AND THEATRE,ARTS,83016743,8.015574,4.120442e+05,36362738,46654005,1.037709e+06,25.115469
10202,7412236,Steve Jobs,122,San Francisco-Bay Area,CA,UNITED STATES,US,USA,37.783333,-122.416667,...,DESIGNER,DESIGN,ARTS,78372660,6.253179,2.303999e+06,45627865,32744795,6.423989e+05,24.406233
7081,5792809,Angelina Jolie,91,Los Angeles,CA,UNITED STATES,US,USA,34.050000,-118.250000,...,ACTOR,FILM AND THEATRE,ARTS,68213700,7.665655,3.002520e+05,34643640,33570060,7.496011e+05,23.078402
7162,19394613,Kim Kardashian,44,Los Angeles,CA,UNITED STATES,US,USA,34.050000,-118.250000,...,CELEBRITY,MEDIA PERSONALITY,PUBLIC FIGURE,66670205,3.628775,3.805552e+05,47834822,18835383,1.515232e+06,19.950031
0,307,Abraham Lincoln,131,Hodgenville,KY,UNITED STATES,US,USA,37.571111,-85.738611,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,66145211,5.801387,5.869147e+05,41477236,24667975,5.049253e+05,27.938585
4344,168540,Lil Wayne,46,New Orleans,LA,United States,US,USA,NaN,NaN,...,SINGER,MUSIC,ARTS,64484487,2.563680,1.919328e+05,52129870,12354617,1.401837e+06,19.545664
4232,19318,Marilyn Monroe,143,Los Angeles,CA,United States,US,USA,34.050000,-118.250000,...,ACTOR,FILM AND THEATRE,ARTS,63671491,8.509241,4.296378e+05,31088742,32582749,4.452552e+05,28.346646
10937,2844938,Mark Zuckerberg,85,Lower Hudson Valley,NY,United States,US,USA,41.040000,-73.778611,...,BUSINESSPERSON,BUSINESS,BUSINESS & LAW,62640549,5.167148,9.535541e+05,39243182,23397367,7.369476e+05,19.533260
10429,16477368,Katy Perry,72,Santa Barbara,CA,UNITED STATES,US,USA,34.425833,-119.714167,...,SINGER,MUSIC,ARTS,61762831,5.347606,3.990784e+05,36463275,25299556,8.578171e+05,20.336693
3382,31341,Tupac Shakur,69,New York,NY,United States,US,USA,NaN,NaN,...,SINGER,MUSIC,ARTS,59789956,5.296006,2.001476e+05,36806550,22983406,8.665211e+05,22.970373
9279,1769827,Megan Fox,63,Oak Ridge,TN,UNITED STATES,US,USA,36.013333,-84.262500,...,ACTOR,FILM AND THEATRE,ARTS,59594557,5.225347,3.732418e+05,33823561,25770996,9.459453e+05,19.892430
10152,5422144,Taylor Swift,68,Reading,PA,United States,US,USA,40.341667,-75.926389,...,ACTOR,FILM AND THEATRE,ARTS,58688243,4.900938,4.224973e+05,37700341,20987902,8.630624e+05,19.046589
179,3382,Britney Spears,94,McComb,MS,UNITED STATES,US,USA,31.244472,-90.471592,...,SINGER,MUSIC,ARTS,58474806,7.014088,1.817315e+05,30872137,27602669,6.220724e+05,22.193222
4626,5119376,John F. Kennedy,116,Boston,MA,UNITED STATES,US,USA,42.331667,-71.121667,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,57596834,6.577612,3.902760e+05,33052400,24544434,4.965244e+05,27.663441
1634,37313,Bruce Lee,84,San Francisco-Bay Area,CA,UNITED STATES,US,USA,37.794722,-122.407222,...,ACTOR,FILM AND THEATRE,ARTS,56281877,7.955667,2.677325e+05,28409150,27872727,6.700223e+05,27.814246
359,9288,Elvis Presley,118,Tupelo,MS,UNITED STATES,US,USA,34.259722,-88.725833,...,SINGER,MUSIC,ARTS,55896331,8.724884,2.059676e+05,26072801,29823530,4.736977e+05,28.617242
3970,154698,Will Smith,74,Philadelphia,PA,United States,US,USA,NaN,NaN,...,ACTOR,FILM AND THEATRE,ARTS,55709750,5.801626,2.466616e+05,30098646,25611104,7.528345e+05,23.438465
7037,2629332,Kristen Stewart,58,Los Angeles,CA,UNITED STATES,US,USA,34.050000,-118.250000,...,ACTOR,FILM AND THEATRE,ARTS,55438548,6.233086,3.820231e+05,29122743,26315805,9.558370e+05,19.224373
1928,44849,Brad Pitt,86,Shawnee,OK,United States,US,USA,35.342500,-96.933889,...,ACTOR,FILM AND THEATRE,ARTS,55005621,7.784188,2.270068e+05,25372370,29633251,6.396002e+05,24.889179
185,3747,Bill Gates,123,Seattle,WA,UNITED STATES,US,USA,47.609722,-122.333056,...,BUSINESSPERSON,BUSINESS,BUSINESS & LAW,54216010,7.804876,2.235868e+05,28776520,25439490,4.407806e+05,26.347717
4373,52711,Leonardo DiCaprio,78,Los Angeles,CA,UNITED STATES,US,USA,34.050000,-118.250000,...,ACTOR,FILM AND THEATRE,ARTS,53901927,6.901818,3.591323e+05,27364717,26537210,6.910503e+05,22.331246
10606,12520860,Demi Lovato,84,Albuquerque,NM,UNITED STATES,US,USA,35.110703,-106.609991,...,SINGER,MUSIC,ARTS,53414996,5.775026,3.133061e+05,29050645,24364351,6.358928e+05,19.251150
3177,83688,Beyoncé,86,Houston,TX,UNITED STATES,US,USA,29.762778,-95.383056,...,SINGER,MUSIC,ARTS,53049791,6.111314,3.464742e+05,31191963,21857828,6.168580e+05,20.990499
3141,20455,Michael Jordan,75,New York,NY,UNITED STATES,US,USA,40.692778,-73.990278,...,BASKETBALL PLAYER,TEAM SPORTS,SPORTS,49879093,5.077657,2.621671e+05,31236048,18643045,6.650546e+05,23.619816
3111,156126,The Rock,45,San Francisco-Bay Area,CA,UNITED STATES,US,USA,37.668889,-122.080833,...,ACTOR,FILM AND THEATRE,ARTS,49588797,4.365728,4.095084e+05,31380680,18208117,1.101973e+06,21.053641
9978,345802,John Cena,53,West Newbury,MA,UNITED STATES,US,USA,42.801389,-70.990278,...,WRESTLER,INDIVIDUAL SPORTS,SPORTS,48740783,5.312118,2.297230e+05,27756660,20984123,9.196374e+05,21.308110
10808,31460,Tom Cruise,82,Syracuse,NY,UNITED STATES,US,USA,43.046944,-76.144444,...,ACTOR,FILM AND THEATRE,ARTS,48511575,6.958255,3.236882e+05,25325423,23186152,5.916046e+05,24.160751
2685,16175,Jennifer Lopez,74,New York,NY,United States,US,USA,NaN,NaN,...,SINGER,MUSIC,ARTS,47371469,7.262349,3.916983e+05,24031252,23340217,6.401550e+05,22.786505
9494,20913246,Scarlett Johansson,91,New York,NY,UNITED STATES,US,USA,40.712700,-74.005900,...,ACTOR,FILM AND THEATRE,ARTS,47029383,6.016915,2.853739e+05,25225160,21804223,5.168064e+05,20.602958
810,16707,Kurt Cobain,68,Aberdeen,WA,UNITED STATES,US,USA,46.975833,-123.818611,...,SINGER,MUSIC,ARTS,46176455,8.048223,1.989637e+05,20350744,25825711,6.790655e+05,23.875487
5920,278119,Charlie Sheen,51,New York,NY,UNITED STATES,US,USA,40.712700,-74.005900,...,ACTOR,FILM AND THEATRE,ARTS,44461809,5.176825,6.421396e+05,25622979,18838830,8.718002e+05,21.937986
3915,61404,Sylvester Stallone,74,New York,NY,UNITED STATES,US,USA,40.712700,-74.005900,...,ACTOR,FILM AND THEATRE,ARTS,43805205,7.467099,2.938003e+05,21338758,22466447,5.919622e+05,26.574520
10925,39942,Jennifer Aniston,70,Los Angeles,CA,UNITED STATES,US,USA,34.151111,-118.448333,...,ACTOR,FILM AND THEATRE,ARTS,43727724,5.654944,2.096388e+05,25563882,18163842,6.246818e+05,22.775085
9857,3414021,George Bush,143,New Haven,CT,UNITED STATES,US,USA,41.310000,-72.923611,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,42866705,5.401050,2.312699e+05,28235452,14631253,2.997672e+05,26.698181
4926,162870,Jay-Z,56,New York,NY,UNITED STATES,US,USA,40.692778,-73.990278,...,SINGER,MUSIC,ARTS,42716217,3.305492,1.721002e+05,32203115,10513102,7.627896e+05,21.642091
5350,192481,50 Cent,67,New York,NY,United States,US,USA,NaN,NaN,...,SINGER,MUSIC,ARTS,42347730,5.934493,1.059849e+05,24758992,17588738,6.320557e+05,22.434486
1282,25169,Quentin Tarantino,68,Knoxville,TN,UNITED STATES,US,USA,35.972778,-83.942222,...,FILM DIRECTOR,FILM AND THEATRE,ARTS,41489929,7.355519,4.087986e+05,17643500,23846429,6.101460e+05,23.510206
7312,523032,Kanye West,54,Atlanta,GA,UNITED STATES,US,USA,33.755000,-84.390000,...,SINGER,MUSIC,ARTS,41382483,2.958805,2.082881e+05,32040185,9342298,7.663423e+05,19.866677
10632,13199916,Taylor Lautner,111,Grand Rapids,MI,UNITED STATES,US,USA,42.961250,-85.655719,...,ACTOR,FILM AND THEATRE,ARTS,40302818,5.936254,3.436550e+05,20943556,19359262,3.630885e+05,18.953321
8724,8490390,Lindsay Lohan,66,New York,NY,UNITED STATES,US,USA,40.712700,-74.005900,...,ACTOR,FILM AND THEATRE,ARTS,40252855,6.207531,1.280371e+05,21306837,18946018,6.098917e+05,20.481059
6729,415175,Vin Diesel,46,New York,NY,UNITED STATES,US,USA,40.712700,-74.005900,...,ACTOR,FILM AND THEATRE,ARTS,39643634,7.056825,3.397942e+05,18948432,20695202,8.618181e+05,22.443938
4166,162617,Chuck Norris,64,Ryan,OK,UNITED STATES,US,USA,34.021667,-97.954167,...,ACTOR,FILM AND THEATRE,ARTS,39583094,7.276117,2.862809e+05,18461401,21121693,6.184858e+05,26.756722
732,16095,Jimi Hendrix,83,Seattle,WA,UNITED STATES,US,USA,47.609722,-122.333056,...,MUSICIAN,MUSIC,ARTS,39460548,7.672650,1.168964e+05,18685074,20775474,4.754283e+05,27.925762
2794,69323,Justin Timberlake,69,Memphis,TN,UNITED STATES,US,USA,35.117365,-89.971068,...,SINGER,MUSIC,ARTS,39421979,5.556528,2.716729e+05,23672034,15749945,5.713330e+05,20.293670

In [105]:
alltop50.to_csv('alltop50.csv')

In [7]:
alltop50.sort_values(by='birthyear', ascending=True)

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
2445,59172,Judas Iscariot,63,Other,NaN,Unknown,UNK,NaN,NaN,NaN,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,11142102,8.395271,76652.454360,5293963,5848139,176858.761900,28.769287
708,15924,Julius Caesar,128,Rome,NaN,Italy,IT,ITA,41.900000,12.500000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,43088745,10.801392,157206.073200,18319789,24768956,336630.820300,31.116139
3666,143102,Saint Anne,52,Bethlehem,NaN,Palestine,PS,PSE,31.703056,35.195556,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,2297429,7.141115,10510.721190,979351,1318078,44181.326920,26.641820
7791,650896,Elizabeth,27,Hebron,NaN,Palestine,PS,PSE,NaN,NaN,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,178935,10.456490,943.807080,1949,176986,6627.222222,24.217614
6393,357200,Queen of Sheba,52,Marib,NaN,Yemen,YE,YEM,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,6021924,8.377006,36938.236860,2842400,3179524,115806.230800,27.644718
6186,332593,Leah,27,Other,NaN,Unknown,UNK,UNK,NaN,NaN,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,1407248,4.597034,4978.614359,917165,490083,52120.296300,25.069644
392,9902,Esther,29,Susa,NaN,Iran,IR,IRN,32.190556,48.257778,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,2951867,2.609404,10464.781970,2360111,591756,101788.517200,24.761271
5617,266088,Jesse,29,Bethlehem,NaN,Palestine,PS,PSE,NaN,NaN,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,1265279,4.686882,4245.630983,836791,428488,43630.310340,25.079065
1399,28329,Solomon,79,Jerusalem,NaN,Israel,IL,ISR,31.783333,35.216667,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,13359813,9.865476,52663.987260,5568945,7790868,169111.557000,29.564853
334,8551,David,72,Bethlehem,NaN,Palestine,PS,PSE,31.703056,35.195556,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,14023246,7.549888,51185.681160,6606099,7417147,194767.305600,29.241855
247,6046,Cicero,83,Arpino,NaN,Italy,IT,ITA,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,13649824,10.972173,44741.587030,5113041,8536783,164455.710800,29.742594
1400,28330,Saul the King,47,Gibeah,NaN,JORDAN,JO,JOR,31.823372,35.231150,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,3113531,7.515378,15961.249830,1548233,1565298,66245.340430,26.924531
10832,18993992,Spartacus,64,Thrace,NaN,Bulgaria,BG,BGR,NaN,NaN,...,MILITARY PERSONNEL,MILITARY,INSTITUTIONS,29683994,7.319395,360810.762000,15160631,14523363,463812.406300,28.299628
3791,148000,Samson,38,Zorah,NaN,Israel,IL,ISR,NaN,NaN,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,6162694,5.752295,33258.499200,3320211,2842483,162176.157900,26.994711
1402,28354,Samuel,40,Other,NaN,Unknown,UNK,UNK,NaN,NaN,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,1746657,5.045604,8468.961616,1069971,676686,43666.425000,25.999055
4019,156607,Nefertari,33,Other,NaN,Egypt,EG,EGY,NaN,NaN,...,COMPANION,COMPANIONS,PUBLIC FIGURE,1855245,7.976670,5805.982435,836883,1018362,56219.545450,26.741732
5294,237521,Seti I,42,Other,NaN,Unknown,UNK,UNK,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1848362,9.089308,5363.283115,879689,968673,44008.619050,27.141225
6520,380296,Ramesses I,37,Other,NaN,Unknown,UNK,UNK,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1355776,11.770376,3825.442183,491777,863999,36642.594590,27.186581
10981,21476519,Ramesses II,59,Other,NaN,Egypt,EG,EGY,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,10524828,9.048805,41057.889800,4995003,5529825,178386.915300,28.923294
1450,30437,Tutankhamun,75,Ancient Egypt,NaN,Egypt,EG,EGY,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,17640463,9.705824,100149.135600,8255195,9385268,235206.173300,29.395324
3260,87868,Posidonius,42,Apamea,NaN,Syria,SY,SYR,35.418000,36.398000,...,PHILOSOPHER,PHILOSOPHY,HUMANITIES,511834,12.613142,1596.163670,177249,334585,12186.523810,26.021175
3310,90050,Nefertiti,74,Thebes,NaN,Egypt,EG,EGY,25.720556,32.610278,...,COMPANION,COMPANIONS,PUBLIC FIGURE,9660479,11.693632,35080.205320,3677405,5983074,130547.013500,29.571094
3302,89728,Akhenaten,62,Other,NaN,Egypt,EG,EGY,26.000000,30.000000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,7197331,10.316981,27352.736060,3062583,4134748,116085.983900,28.856018
5494,253776,Amenhotep III,45,Other,NaN,Unknown,UNK,UNK,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1605312,10.066622,6378.891638,705937,899375,35673.600000,26.942628
935,19577,Moses,115,Wadi Tumilat,NaN,Egypt,EG,EGY,NaN,NaN,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,21880195,12.688834,83770.444220,8322104,13558091,190262.565200,30.863247
24,1006,Aaron,59,Other,NaN,Egypt,EG,EGY,NaN,NaN,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,2819250,6.451532,9444.915640,1587626,1231624,47783.898310,27.602094
3994,155730,Thutmose III,48,Other,NaN,Unknown,UNK,NaN,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,2314325,10.479395,9737.107416,964420,1349905,48215.104170,27.415752
4714,191497,Sarah,37,Other,NaN,Unknown,UNK,UNK,NaN,NaN,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,3352644,4.621298,9474.022625,2090286,1262358,90612.000000,26.996681
2494,60832,Hatshepsut,57,Other,NaN,Egypt,EG,EGY,26.000000,30.000000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,5409146,7.726790,18352.192570,2846959,2562187,94897.298250,26.743618
737,16121,Joshua,41,Other,NaN,Egypt,EG,EGY,NaN,NaN,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,3819284,4.845047,14924.899010,2484555,1334729,93153.268290,26.563327
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1353,26560,Rurik,45,Other,NaN,Unknown,UNK,UNK,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,2164558,5.411059,11294.132410,489506,1675052,48101.288890,25.909601
6297,344687,Muhammad ibn Jarir al-Tabari,35,Amol,NaN,Iran,IR,IRN,36.469722,52.350833,...,HISTORIAN,HISTORY,HUMANITIES,702379,7.778789,4055.920707,322726,379653,20067.971430,24.430613
5959,310317,Árpád,33,Hungary,NaN,Hungary,HU,HUN,47.433333,19.250000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,670934,10.924177,3020.682943,211904,459030,20331.333330,25.145791
2386,56251,Harald I of Norway,35,Rogaland,NaN,NORWAY,NO,NOR,58.972700,6.910400,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,775656,10.576105,2872.608798,169429,606227,22161.600000,25.642595
6969,434293,Mansur Al-Hallaj,27,Fars Province,NaN,Iran,IR,IRN,29.616667,52.533333,...,WRITER,LANGUAGE,HUMANITIES,820023,8.414569,9904.533130,274051,545972,30371.222220,23.862637
3057,78209,Al-Razi,50,Ray,NaN,Iran,IR,IRN,35.583333,51.433333,...,PHYSICIAN,MEDICINE,SCIENCE & TECHNOLOGY,2108654,6.505246,52999.270700,552778,1555876,42173.080000,24.531496
6252,339877,Simeon I of Bulgaria,39,Bulgaria,NaN,Bulgaria,BG,BGR,42.750000,25.500000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,962596,6.385019,3860.841768,230187,732409,24681.948720,25.345518
6945,430239,Muhammad al-Mahdi,26,Samarra,NaN,Iraq,IQ,IRQ,34.198333,43.874167,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,1819996,6.394447,7207.923268,943952,876044,69999.846150,25.132007
4481,175040,Al-Farabi,52,Otrar,NaN,Kazakhstan,KZ,KAZ,42.852500,68.302778,...,PHILOSOPHER,PHILOSOPHY,HUMANITIES,2870185,9.809685,19767.504690,585944,2284241,55195.865380,26.656889
10514,10219069,Ali al-Masudi,41,Baghdad,NaN,Iraq,IQ,IRQ,33.333333,44.433333,...,WRITER,LANGUAGE,HUMANITIES,354845,13.337372,2509.967080,114740,240105,8654.756098,24.430426
1130,23979,Ptolemy,87,Egypt,NaN,Egypt,EG,EGY,31.200000,29.916667,...,ASTRONOMER,NATURAL SCIENCES,SCIENCE & TECHNOLOGY,9459640,9.855571,35640.649090,3644302,5815338,108731.494300,29.089163
1803,42419,Harald I of Denmark,39,Jelling,NaN,Denmark,DK,DNK,55.753611,9.415000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1371881,9.750446,7391.755571,464547,907334,35176.435900,25.659656
991,20597,Mieszko I of Poland,43,Other,NaN,Unknown,UNK,UNK,NaN,NaN,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,2620063,2.777623,13787.448670,233890,2386173,60931.697670,25.478935
4749,193580,Ferdowsi,68,Tous,NaN,Iran,IR,IRN,36.454167,59.566944,...,WRITER,LANGUAGE,HUMANITIES,1588037,8.433054,9349.762052,461762,1126275,23353.485290,26.178047
3055,77931,Brian Boru,30,Killaloe,NaN,Ireland,IE,IRL,52.800000,-8.450000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1047078,3.502897,3519.389107,775466,271612,34902.600000,23.618767
1765,40606,Sviatoslav I of Kiev,43,Kiev,NaN,UKRAINE,UA,UKR,50.450000,30.523333,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1482355,4.630231,10745.597130,240179,1242176,34473.372090,25.008779
3230,85836,Erik the Red,47,Other,NaN,Iceland,IS,ISL,61.000000,8.000000,...,EXPLORER,EXPLORERS,EXPLORATION,2510710,8.485465,7711.195892,1183434,1327276,53419.361700,26.623086
129,2108,Adalbert of Prague,31,Libice nad Cidlinou,NaN,CZECH REPUBLIC,CZ,CZE,50.127778,15.180278,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,1637769,3.535056,9166.329036,142254,1495515,52831.258060,24.846465
2020,46547,Samuil of Bulgaria,30,Prilep,NaN,Republic of Macedonia,MK,MKD,41.344444,21.552778,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,648353,7.610644,3432.801735,126960,521393,21611.766670,24.580911
1752,40406,Sweyn I of Denmark,44,Denmark,NaN,Denmark,DK,DNK,55.720000,12.570000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,990758,11.052150,4259.515452,379536,611222,22517.227270,25.702824
2718,66278,Olaf I of Norway,27,Norway,NaN,Norway,NO,NOR,61.000000,8.000000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,628928,8.566237,2165.901125,215432,413496,23293.629630,24.788670
79,1645,Ibn al-Haitham,53,Basra,NaN,Iraq,IQ,IRQ,30.500000,47.816667,...,PHYSICIST,NATURAL SCIENCES,SCIENCE & TECHNOLOGY,3158260,6.024090,57838.722700,763193,2395067,59589.811320,25.195144
1431,29594,Stephen I of Hungary,46,Esztergom,NaN,HUNGARY,HU,HUN,47.785556,18.740278,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1552816,7.744655,10379.218160,491292,1061524,33756.869570,25.497548
3740,146803,Leif Ericson,70,Other,NaN,Iceland,IS,ISL,65.000000,-18.000000,...,EXPLORER,EXPLORERS,EXPLORATION,4615953,5.356456,23348.221750,2996467,1619486,65942.185710,26.247766
7796,651860,Mahmud of Ghazni,37,Ghazni,NaN,AFGHANISTAN,AF,AFG,33.550000,68.416667,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1412061,3.925809,7971.166500,965986,446075,38163.810810,23.899611
5640,271975,Al-Biruni,59,Khwarezm,NaN,Iran,IR,IRN,NaN,NaN,...,MATHEMATICIAN,MATH,SCIENCE & TECHNOLOGY,2515834,10.826043,69105.767010,404188,2111646,42641.254240,25.351710
9382,1989064,Al-Ma'arri,28,Maarat Al-Numaan,NaN,Syria,SY,SYR,35.638611,36.671667,...,WRITER,LANGUAGE,HUMANITIES,657055,4.021884,5977.887567,79036,578019,23466.250000,23.425535
32,1130,Avicenna,102,Bukhara,NaN,UZBEKISTAN,UZ,UZB,39.766667,64.433333,...,PHILOSOPHER,PHILOSOPHY,HUMANITIES,10026549,12.307475,56379.949590,2408563,7617986,98299.500000,28.891726
1758,40501,Canute the Great,54,Other,NaN,Denmark,DK,DNK,55.720000,12.570000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,2319498,7.487515,14826.710320,1288922,1030576,42953.666670,25.623154
3875,150695,Olaf II of Norway,33,Ringerike,NaN,NORWAY,NO,NOR,60.205278,10.152500,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,975295,7.681027,4521.893647,333004,642291,29554.393940,25.000962

In [18]:
alltop50[alltop50['name'] == 'Olaf II of Norway'].birthyear

3875    995
Name: birthyear, dtype: object

In [9]:
df[df['name'] == 'Julius Caesar'].birthyear

708    -100
Name: birthyear, dtype: object

In [11]:
df_alltop50_recent = alltop50[alltop50['birthyear'].astype(int) > -500 ] # only people who were born after -500

In [18]:
df_alltop50_recent.countryCode.value_counts()

IE    50
IT    50
US    50
FI    50
IN    50
CA    50
SE    50
RO    50
UA    50
PT    50
RU    50
BR    50
MX    50
AT    50
DK    50
FR    50
JP    50
HU    50
AU    50
AR    50
CH    50
PL    50
NL    50
ES    50
NO    50
RS    50
CZ    50
DE    50
GB    50
HR    50
      ..
NC     1
GY     1
BB     1
QA     1
SC     1
BI     1
BH     1
GQ     1
MR     1
FO     1
LI     1
AD     1
AW     1
SL     1
NR     1
NE     1
WS     1
AG     1
GM     1
GI     1
MU     1
BM     1
DJ     1
FM     1
KI     1
LA     1
ER     1
BN     1
LS     1
VU     1
Name: countryCode, Length: 195, dtype: int64

In [12]:
df_alltop50_recent.to_csv('alltop50_recent.csv')

# Brazil + US

In [12]:
frames = [dfbr, dfus]

df_br_us = pd.concat(frames)
df_br_us.shape

(2305, 23)

In [151]:
top50_br_us = df_br_us.sort_values(by='TotalPageViews', ascending=False).head(50)
top50_br_us.to_csv('top50_br_us.csv')

In [8]:
brazil100.domain.value_counts()

SPORTS                  69
INSTITUTIONS            12
ARTS                    10
PUBLIC FIGURE            4
HUMANITIES               4
SCIENCE & TECHNOLOGY     1
Name: domain, dtype: int64

In [13]:
df_br_us

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
1275,24953,Pelé,88,Três Corações,NaN,BRAZIL,BR,BRA,-21.694722,-45.255278,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,24153197,10.422685,125882.721700,8748518,15404679,274468.147700,27.446571
2093,48372,Oscar Niemeyer,68,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,ARCHITECT,DESIGN,ARTS,6674328,7.823341,114605.368400,1498447,5175881,98151.882350,24.887963
2682,65145,Paulo Coelho,69,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,WRITER,LANGUAGE,HUMANITIES,14311386,10.698883,72606.512690,4185642,10125744,207411.391300,26.192696
2713,66164,Ronaldo,75,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,38313289,11.197644,210732.889400,14546961,23766328,510843.853300,22.533707
2790,68997,Fernando Collor de Mello,32,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,2470866,2.627431,20068.808580,261770,2209096,77214.562500,21.719184
3144,81473,Pedro II of Brazil,43,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,2794865,3.510417,15826.569040,789440,2005425,64996.860470,24.202779
3163,82491,Fernando Henrique Cardoso,37,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,2557129,3.818594,15911.177200,426935,2130194,69111.594590,23.504252
3408,99328,Luiz Inácio Lula da Silva,80,Caetés,Pernambuco,BRAZIL,BR,BRA,-8.772800,-36.622800,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,7558871,5.820781,54144.537440,1628304,5930567,94485.887500,25.159262
3734,146638,Ayrton Senna,64,São Paulo,NaN,BRAZIL,BR,BRA,-23.550000,-46.633333,...,RACECAR DRIVER,INDIVIDUAL SPORTS,SPORTS,18835095,9.530541,102857.616400,6642249,12192846,294298.359400,24.098599
3926,152687,Alberto Santos-Dumont,30,Santos Dumont,NaN,BRAZIL,BR,BRA,-21.456667,-43.552500,...,INVENTOR,INVENTION,SCIENCE & TECHNOLOGY,2995065,3.381319,25010.594850,531689,2463376,99835.500000,23.409904
4185,163094,Eurico Gaspar Dutra,27,Cuiabá,NaN,BRAZIL,BR,BRA,-15.595833,-56.096944,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,657041,2.683388,4457.293158,59642,597399,24334.851850,21.810980
4422,172002,Peter Medawar,35,Petrópolis,NaN,BRAZIL,BR,BRA,-22.505000,-43.178889,...,BIOLOGIST,NATURAL SCIENCES,SCIENCE & TECHNOLOGY,392202,8.299716,1523.507145,195655,196547,11205.771430,22.441677
4512,177278,Caetano Veloso,28,Santo Amaro,NaN,BRAZIL,BR,BRA,-12.546944,-38.711944,...,MUSICIAN,MUSIC,ARTS,2722713,4.973743,10719.673490,621032,2101681,97239.750000,23.830136
4513,177293,Gilberto Gil,32,Salvador,NaN,BRAZIL,BR,BRA,-12.974722,-38.476667,...,MUSICIAN,MUSIC,ARTS,1799746,5.868146,5884.284670,439342,1360404,56242.062500,23.879890
4514,177304,Heitor Villa-Lobos,38,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,COMPOSER,MUSIC,ARTS,2442874,6.225506,15931.347580,532653,1910221,64286.157890,24.173586
4548,179202,José Sarney,31,Pinheiro,NaN,BRAZIL,BR,BRA,-2.520833,-45.082778,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1611679,2.709214,11339.618640,188187,1423492,51989.645160,22.466852
4908,204645,Nelson Piquet,36,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,RACECAR DRIVER,INDIVIDUAL SPORTS,SPORTS,2253732,9.595009,8798.561535,665400,1588332,62603.666670,23.071700
5345,241678,Emerson Fittipaldi,34,São Paulo,NaN,BRAZIL,BR,BRA,-23.550000,-46.633333,...,RACECAR DRIVER,INDIVIDUAL SPORTS,SPORTS,1795935,9.398485,9304.433310,619906,1176029,52821.617650,23.335160
5479,252989,Rubens Barrichello,50,São Paulo,NaN,BRAZIL,BR,BRA,-23.550000,-46.633333,...,RACECAR DRIVER,INDIVIDUAL SPORTS,SPORTS,3441875,9.016159,17412.906860,1418512,2023363,68837.500000,20.177126
5507,254397,Maria II of Portugal,31,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,880468,5.147712,2710.025647,278065,602403,28402.193550,23.688007
5555,258947,Rivaldo,52,Paulista,NaN,BRAZIL,BR,BRA,-7.940833,-34.872778,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,9225397,10.983897,42095.491970,3161879,6063518,177411.480800,21.614502
5832,297412,Antônio Carlos Jobim,39,Tijuca,NaN,BRAZIL,BR,BRA,-22.925510,-43.252140,...,MUSICIAN,MUSIC,ARTS,1967630,7.724191,12513.281020,356802,1610828,50452.051280,23.994438
6003,314055,Juscelino Kubitschek de Oliveira,39,Diamantina,NaN,BRAZIL,BR,BRA,-18.249000,-43.600000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,3370083,2.279152,20548.032620,207060,3163023,86412.384620,23.674873
6064,319743,Joaquim Maria Machado de Assis,30,Rio de Janeiro,NaN,BRAZIL,BR,BRA,-22.908333,-43.196389,...,WRITER,LANGUAGE,HUMANITIES,4576905,1.596897,36498.581840,167705,4409200,152563.500000,23.444774
6463,365451,Itamar Franco,41,Salvador,NaN,Brazil,BR,BRA,0.000000,-30.000000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1176290,3.924297,15679.375000,171615,1004675,28690.000000,22.129562
6468,367760,Deodoro da Fonseca,37,Marechal Deodoro,NaN,BRAZIL,BR,BRA,-9.710000,-35.895000,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,1264108,2.822574,9132.741066,103460,1160648,34165.081080,23.036226
6903,421320,Jorge Amado,40,Itabuna,NaN,BRAZIL,BR,BRA,-14.785833,-39.280000,...,WRITER,LANGUAGE,HUMANITIES,2540049,4.259316,27051.652870,226757,2313292,63501.225000,23.386800
7063,454123,Roberto Carlos da Silva,56,Garça,Sao Paulo,Brazil,BR,BRA,-22.215278,-49.651111,...,SOCCER PLAYER,TEAM SPORTS,SPORTS,5347640,11.923369,36149.277850,109516,5238124,95493.571430,21.070663
7175,483149,Gustavo Kuerten,39,Florianópolis,NaN,BRAZIL,BR,BRA,-27.571700,-48.625600,...,TENNIS PLAYER,INDIVIDUAL SPORTS,SPORTS,2217638,7.649363,19163.755250,774249,1443389,56862.512820,18.245640
7213,492058,Ernesto Geisel,29,Bento Gonçalves,NaN,Brazil,BR,BRA,-29.170833,-51.518889,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,932978,3.502989,5933.893185,119680,813298,32171.655170,22.374760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11115,24318105,Candice Accola,26,Houston,TX,UNITED STATES,US,USA,29.762778,-95.383056,...,ACTOR,FILM AND THEATRE,ARTS,4564581,5.750469,55042.309840,2349578,2215003,175560.807700,15.823962
11125,24604691,Thomas A. Steitz,36,Milwaukee,WI,UNITED STATES,US,USA,43.050000,-87.950000,...,CHEMIST,NATURAL SCIENCES,SCIENCE & TECHNOLOGY,262960,10.845992,5402.759815,109645,153315,7304.444444,20.610903
11126,24626957,David J. Wineland,39,Milwaukee,WI,United States,US,USA,43.050000,-87.950000,...,PHYSICIST,NATURAL SCIENCES,SCIENCE & TECHNOLOGY,334447,6.704726,17088.735900,192101,142346,8575.564103,19.041188
11139,766618,Alyson Michalka,26,Los Angeles,CA,UNITED STATES,US,USA,33.834722,-118.341389,...,ACTOR,FILM AND THEATRE,ARTS,3111096,6.650449,27684.070780,1335725,1775371,119657.538500,15.708561
11141,25426557,Larry Sanger,48,Bellevue,WA,United States,US,USA,47.600000,-122.166667,...,INVENTOR,INVENTION,SCIENCE & TECHNOLOGY,1604366,8.955391,10836.847170,876288,728078,33424.291670,19.456984
11144,1061132,Daryl Sabara,30,Los Angeles,CA,UNITED STATES,US,USA,33.834722,-118.341389,...,ACTOR,FILM AND THEATRE,ARTS,3511506,2.813105,24292.468500,2655111,856395,117050.200000,13.989100
11150,418309,Daniel Carleton Gajdusek,35,Lower Hudson Valley,NY,UNITED STATES,US,USA,40.941389,-73.864444,...,PHYSICIAN,MEDICINE,SCIENCE & TECHNOLOGY,431931,8.811987,3573.030586,142197,289734,12340.885710,22.072292
11151,18600829,Jeff Gordon,40,San Francisco-Bay Area,CA,UNITED STATES,US,USA,38.113056,-122.235833,...,RACECAR DRIVER,INDIVIDUAL SPORTS,SPORTS,2681998,2.307018,33302.426610,2262271,419727,67049.950000,16.280375
11154,25778629,Thomas Samuel Kuhn,42,Cincinnati,OH,UNITED STATES,US,USA,39.100000,-84.516667,...,HISTORIAN,HISTORY,HUMANITIES,3335957,9.038304,14098.253730,936769,2399188,79427.547620,25.073477
11183,77934,Kevin Mitnick,39,Los Angeles,CA,UNITED STATES,US,USA,34.183300,-118.433300,...,COMPUTER SCIENTIST,COMPUTER SCIENCE,SCIENCE & TECHNOLOGY,4964483,8.118333,13175.751610,2235423,2729060,127294.435900,22.196960
11195,26713474,Rick Santorum,36,Winchester,VA,United States,US,USA,39.183333,-78.166667,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,7820622,1.658530,307425.037600,7131064,689558,217239.500000,17.240701
11196,26807275,Jesse James,36,Kearney,MO,UNITED STATES,US,USA,39.365833,-94.360278,...,MAFIOSO,OUTLAWS,PUBLIC FIGURE,15456944,3.952988,57602.783360,10267837,5189107,429359.555600,25.423159
11197,684753,Robert B. Laughlin,40,Visalia,CA,UNITED STATES,US,USA,36.316667,-119.300000,...,PHYSICIST,NATURAL SCIENCES,SCIENCE & TECHNOLOGY,333781,12.833747,1368.952780,114407,219374,8344.525000,21.747904
11199,26889895,Colonel Sanders,26,Henryville,IN,UNITED STATES,US,USA,38.541111,-85.766667,...,BUSINESSPERSON,BUSINESS,BUSINESS & LAW,4378765,4.158510,28418.056180,2695231,1683534,168414.038500,23.251748
11201,27005455,Bruno Mars,53,Honolulu,HI,UNITED STATES,US,USA,21.300000,-157.816667,...,SINGER,MUSIC,ARTS,38317635,5.138599,509755.209800,23206228,15111407,722974.245300,18.584779
11208,27333510,Greyson Michael Chance,26,Wichita Falls,TX,UNITED STATES,US,USA,33.896944,-98.515000,...,MUSICIAN,MUSIC,ARTS,4346540,3.154302,63972.490330,3169805,1176735,167174.615400,12.612849
11215,27630477,Bradley Manning,29,Crescent,OK,United States,US,USA,35.953056,-97.594722,...,MILITARY PERSONNEL,MILITARY,INSTITUTIONS,5028336,2.904552,119846.818800,3789325,1239011,173390.896600,13.987869
11220,27834683,Matthew McConaughey,36,Uvalde,TX,UNITED STATES,US,USA,29.214444,-99.789722,...,ACTOR,FILM AND THEATRE,ARTS,14874441,4.387562,75347.799000,9258867,5615574,413178.916700,20.627396
11232,269416,Tim Robbins,41,Los Angeles,CA,United States,US,USA,34.056667,-117.918611,...,ACTOR,FILM AND THEATRE,ARTS,8003812,5.355022,29286.896090,4675966,3327846,195214.926800,22.491132
11238,84317,Ansel Adams,37,San Francisco-Bay Area,CA,UNITED STATES,US,USA,37.782519,-122.428250,...,PHOTOGRAPHER,FINE ARTS,ARTS,4152641,3.909851,18775.870590,2933187,1219454,112233.540500,23.507800
11248,29818009,Douglas Fairbanks,29,Denver,CO,UNITED STATES,US,USA,39.761850,-104.881105,...,ACTOR,FILM AND THEATRE,ARTS,2059703,4.119730,7918.283285,1389851,669852,71024.241380,22.993556
11260,12230,Gary Coleman,29,Zion,IL,UNITED STATES,US,USA,42.453221,-87.840222,...,ACTOR,FILM AND THEATRE,ARTS,11012150,3.877104,229957.454400,7154092,3858058,379729.310300,18.654751
11270,541035,John Howard Northrop,36,Lower Hudson Valley,NY,UNITED STATES,US,USA,40.941389,-73.864444,...,CHEMIST,NATURAL SCIENCES,SCIENCE & TECHNOLOGY,198918,16.800742,841.305100,40670,158248,5525.500000,23.031257
11286,174821,Heather Locklear,29,Los Angeles,CA,UNITED STATES,US,USA,34.056110,-118.429720,...,ACTOR,FILM AND THEATRE,ARTS,8224876,4.284104,36098.714940,5002824,3222052,283616.413800,21.238523
11297,32387701,"Joseph Smith, Jr.",66,Sharon,VT,United States,US,USA,43.773611,-72.443889,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,3572289,4.957041,32935.491960,2322607,1249682,54125.590910,24.088828
11300,32817065,Otis Redding,33,Dawson,GA,UNITED STATES,US,USA,31.773889,-84.440833,...,SINGER,MUSIC,ARTS,5873968,4.204464,25719.032660,3820240,2053728,177999.030300,23.707172
11305,63083,Henry Miller,42,New York,NY,United States,US,USA,NaN,NaN,...,WRITER,LANGUAGE,HUMANITIES,4421069,7.133032,10730.223520,2154712,2266357,105263.547600,25.545865
11311,33576107,Clifford D. Simak,29,Millville,WI,UNITED STATES,US,USA,43.033333,-90.930000,...,WRITER,LANGUAGE,HUMANITIES,458863,7.350770,1355.009452,232019,226844,15822.862070,22.626488
11319,1040267,Sasha Cohen,26,Los Angeles,CA,UNITED STATES,US,USA,34.056110,-118.429720,...,ACTOR,FILM AND THEATRE,ARTS,2142774,3.756356,21558.527090,1346076,796698,82414.384620,15.064043
11330,25473,Richard Nixon,103,Los Angeles,CA,UNITED STATES,US,USA,33.888551,-117.813231,...,POLITICIAN,GOVERNMENT,INSTITUTIONS,27325221,5.129822,94944.979180,18106464,9218757,265293.407800,27.014081

In [7]:
brazil100 = dfbr.sort_values(by='TotalPageViews', ascending=False).head(100)

us100 = dfus.sort_values(by='TotalPageViews', ascending=False).head(100)
us100.shaper

(100, 23)

In [17]:
frames = [brazil100, us100]

df_br_us = pd.concat(frames)
df_br_us.shape
df_br_us.to_csv('50top_brus.csv')

In [25]:
brazil50 = dfbr.sort_values(by='TotalPageViews', ascending=False).head(50)

us50 = dfus.sort_values(by='TotalPageViews', ascending=False).head(50)

frames = [brazil50, us50]

df_brus50 = pd.concat(frames)
df_brus50.shape
df_brus50.to_csv('brazilus50.csv')

In [6]:
brazil100.shape

(100, 23)

In [26]:
brazil50['image_path'] = 'images/' + brazil50['name'].str.lower().str.replace(' ', '-') + '.png'

In [28]:
brazil50
brazil50.to_csv('brasil50new.csv')

In [8]:
us100.domain.value_counts()

ARTS                    74
INSTITUTIONS             8
SPORTS                   7
PUBLIC FIGURE            5
BUSINESS & LAW           3
HUMANITIES               2
SCIENCE & TECHNOLOGY     1
Name: domain, dtype: int64

In [9]:
brazil100.domain.value_counts()

SPORTS                  69
INSTITUTIONS            12
ARTS                    10
PUBLIC FIGURE            4
HUMANITIES               4
SCIENCE & TECHNOLOGY     1
Name: domain, dtype: int64

In [19]:
df[df['name'] == 'Jesus Christ']

,en_curid,name,numlangs,birthcity,birthstate,countryName,countryCode,countryCode3,LAT,LON,...,occupation,industry,domain,TotalPageViews,L_star,StdDevPageViews,PageViewsEnglish,PageViewsNonEnglish,AverageViews,HPI
8689,1095706,Jesus Christ,214,Judea,NaN,Israel,IL,ISR,32.5,34.9,...,RELIGIOUS FIGURE,RELIGION,INSTITUTIONS,60299092,12.10741,257209.9608,25370206,34928886,281771.4579,31.89813